#小米5
platformName: Android
platformVersion: 7.0
deviceName: f5568750
app: DFYJ_SIT.apk
appPackage: com.dfzq.winner
appActivity: com.dfzq.winner.major.activity.LaunchActivity
noReset: true
unicodeKeyboard: true
resetKeyboard: true
ip: 127.0.0.1
port: 4723
automationName: Uiautomator2